# syntax=docker/dockerfile:1

FROM node:16 AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:16 
ENV NODE_ENV=production
WORKDIR /usr/app
COPY package*.json yarn.lock ./
RUN yarn install
COPY --from=build /app/dist ./dist
COPY ./emails ./emails
COPY ./locales ./locales
EXPOSE 4000
CMD npx --yes dotenv-vault@latest pull production .env --dotenvMe $DOTENV_ME;  yarn start 