type Mutation {
  loginToAdmin(input: AdminLoginInput!): AuthMutationResponse!
}

type Query {
  users(page: Page): UserList!
  roles(page: Page): RoleList!
  permissions(page: Page): PermissionList!
}
