type Mutation {
  loginToAdmin(input: AdminLoginInput!): AuthMutationResponse!
}

type Query {
  users(page: Page): UserList! @auth
  roles(page: Page): RoleList! @auth
  permissions(page: Page): PermissionList! @auth
}
