enum SocialProvider {
  GOOGLE
  FACEBOOK
}

input EmailLoginInput {
  email: String!
  password: String!
}

input VerifySMSOTPInput {
  phoneNumber: String!
  token: String!
}

input VerifyEmailOTPInput {
  email: String!
  token: String!
}

input SocialLoginInput {
  provider: SocialProvider!
  token: String!
}

input PasswordResetInput {
  password: String!
  token: String!
}

type Mutation {
  requestPasswordReset(email: String!): RequestResponse!
  requestDeleteAccount: RequestResponse!
  requestSMSOTP(phoneNumber: String!): RequestResponse!
  requestEmailOTP(email: String!): RequestResponse!
  verifySMSOTP(input: VerifySMSOTPInput!): AuthMutationResponse!
  verifyEmailOTP(input: VerifyEmailOTPInput!): AuthMutationResponse!
  registerWithEmail(input: CreateUserInput!): AuthFormMutationResponse!
  loginWithEmail(input: EmailLoginInput!): AuthFormMutationResponse!
  loginWithSocialProvider(input: SocialLoginInput!): AuthMutationResponse!
  resetPassword(input: PasswordResetInput!): AuthFormMutationResponse!
  deleteAccount(token: String!): AuthMutationResponse!
  logout: AuthMutationResponse!
}

type AuthFormMutationResponse implements Response & FormErrors {
  code: Int!
  success: Boolean!
  message: String!
  errors: [FieldError!]
  idToken: String
  accessToken: String
  refreshToken: String
}

type AuthMutationResponse implements Response {
  code: Int!
  success: Boolean!
  message: String!
  idToken: String
  accessToken: String
  refreshToken: String
}
