scalar Date
scalar DateTime

enum ImageResizeMode {
  cover
  contain
  fill
  inside
  outside
}

"""
All Queries and Mutations must implement this interface
"""
interface Response {
  code: ID!
  success: Boolean!
  message: String!
}

"""
All Form mutations, e.g Login, Register, etc must implement this interface to return validation errors
"""
interface FormErrors {
  errors: [FieldError!]
}

"https://sharp.pixelplumbing.com/api-resize#resize"
input ImageResizeInput {
  width: Int!
  height: Int!
  fit: ImageResizeMode
  thumbnailSize: Int = 32
}

type RequestResponse implements Response {
  code: ID!
  success: Boolean!
  message: String!
}

type RequestFormResponse implements Response & FormErrors {
  code: ID!
  success: Boolean!
  message: String!
  errors: [FieldError!]
}

type FieldError {
  message: String!
  field: String!
}

type Photo {
  url: String!
  thumbnail: String
}

type File {
  id: ID!
  size: Int!
  name: String!
  mimeType: String!
  createdAt: DateTime!
  updatedAt: DateTime
}

# Pagination

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: ID
  endCursor: ID
}

enum OrderDirection {
  ASC
  DESC
}

"""
Including a value for both first and last is strongly discouraged,
as it is likely to lead to confusing queries and results.
"""
input ConnectionPage {
  before: ID
  after: ID
  first: Int = 20
  last: Int = 20
}

interface Connection {
  totalCount: Int!
  pageInfo: PageInfo!
}

input ListPage {
  limit: Int
  cursor: ID
  order: String
  direction: OrderDirection
}

interface List {
  nextCursor: ID
  totalCount: Int!
}
