"""
Based on Sequelize operators
https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#operators
"""
input IDFieldFilter {
  eq: ID
  ne: ID
  is: ID
  or: [IDFieldFilter!]
  and: [IDFieldFilter!]
  not: [IDFieldFilter!]

  in: [ID!]
  notIn: [ID!]
  any: [ID!]
}

input NumberFieldFilter {
  eq: Int
  ne: Int
  is: Int
  or: [NumberFieldFilter!]
  and: [NumberFieldFilter!]
  not: [NumberFieldFilter!]

  gt: Int
  gte: Int
  lt: Int
  lte: Int
  between: [Int!]
  notBetween: [Int!]

  in: [Int!]
  notIn: [Int!]
  any: [Int!]
}

input StringFieldFilter {
  eq: String
  ne: String
  is: String
  and: [StringFieldFilter!]
  or: [StringFieldFilter!]
  not: [StringFieldFilter!]

  in: [String!]
  notIn: [String!]
  like: String
  notLike: String
  startsWith: String
  endsWith: String
  substring: String
  iLike: String
  notILike: String
  regexp: String
  notRegexp: String
  iRegexp: String
  notIRegexp: String
  any: [String!]
}

input DateTimeFieldFilter {
  eq: DateTime
  ne: DateTime
  is: DateTime
  and: [DateTimeFieldFilter!]
  or: [DateTimeFieldFilter!]
  not: [DateTimeFieldFilter!]

  gt: DateTime
  gte: DateTime
  lt: DateTime
  lte: DateTime
  between: [DateTime!]
  notBetween: [DateTime!]
  any: [DateTime!]
}

input DateFieldFilter {
  eq: Date
  ne: Date
  is: Date
  and: [DateFieldFilter!]
  or: [DateFieldFilter!]
  not: [DateFieldFilter!]

  gt: Date
  gte: Date
  lt: Date
  lte: Date
  between: [Date!]
  notBetween: [Date!]
  any: [Date!]
}

input BooleanFieldFilter {
  is: Boolean
}
