type Query {
  """
  {
    "en": "English"
  }
  """
  getLocales: JSON!
  getCountries: [Country]!
  """
  {
    "Africa/Lagos":"+01:00"
  }
  """
  getTimeZones: JSON!
}

type Country {
  name: String!
  code: CountryCode!
  dialCode: String!
  phoneNumberPattern: String!
  phoneNumberPlaceholder: String!
}
