type Query {
  getLocales: JSON!
  getCountries: [Country]!
}

type Country {
  name: String!
  code: CountryCode!
  phoneNumberPrefix: String!
  phoneNumberPattern: String!
  phoneNumberPlaceholder: String!
}
