type Query {
  getLocales: [LocaleData]!
  getCountries: [Country]!
  getTimeZones: [TimeZoneData]!
}

type LocaleData {
  code: Locale!
  name: String!
}

type TimeZoneData {
  timeZone: TimeZone!
  offset: UtcOffset!
}

type Country {
  name: String!
  code: CountryCode!
  dialCode: String!
  phoneNumberPattern: String!
  phoneNumberPlaceholder: String!
}
