type Query {
  getLocales: [LocalePayload]!
  getCountries: [Country]!
  getTimeZones: [TimeZonePayload]!
}

type LocalePayload {
  code: Locale!
  name: String!
}

type TimeZonePayload {
  timeZone: TimeZone!
  offset: UtcOffset!
}

type Country {
  name: String!
  code: CountryCode!
  dialCode: String!
  phoneNumberPattern: String!
  phoneNumberPlaceholder: String!
}
