type Query {
  getRoleById(id: ID!): RolePayload!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  roles(page: ListPage, filter: RoleFilter): RoleList!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
}

type Mutation {
  createRole(input: CreateRoleInput!): RoleMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  updateRole(input: UpdateRoleInput!): RoleMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  deleteRole(id: ID!, reason: String): DeleteMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  addPermissionsToRole(
    roleId: ID!
    permissionIds: [ID!]!
  ): RoleMutationResponse! @auth(rules: [{ allow: role, roles: ["admin"] }])
  addUsersToRole(roleId: ID!, userIds: [ID!]!): RoleMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  removeUsersFromRole(roleId: ID!, userIds: [ID!]!): RoleMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
  removePermissionsFromRole(
    roleId: ID!
    permissionIds: [ID!]!
  ): RoleMutationResponse! @auth(rules: [{ allow: role, roles: ["admin"] }])
  removeAllMembersFromRole(roleId: ID!): RoleMutationResponse!
    @auth(rules: [{ allow: role, roles: ["admin"] }])
}

type Role {
  id: ID!
  name: String!
  description: String
  permissions: [Permission]!
  members(page: ListPage, where: UserAttributesWhere): UserList!
  createdAt: DateTime!
  updatedAt: DateTime
}

type RoleList implements List {
  items: [Role]!
  totalCount: Int!
  pageInfo: PageInfo!
}

type RoleMutationResponse implements Response & FormErrors {
  code: ID!
  success: Boolean!
  message: String!
  role: Role
  errors: [FieldError!]
}

type RolePayload implements Response {
  code: ID!
  success: Boolean!
  message: String!
  role: Role
}

# Inputs

input CreateRoleInput {
  name: String!
  description: String
  permissionIds: [ID!]
}

input UpdateRoleInput {
  id: ID!
  name: String
  description: String
}

input RoleFilter {
  where: RoleAttributesWhere
  include: RoleAssociationInclude
}

input RoleAttributesWhere {
  id: IDFieldFilter
  name: StringFieldFilter
  createdAt: DateTimeFieldFilter
  updatedAt: DateTimeFieldFilter
  and: [RoleAttributesWhere!]
  or: [RoleAttributesWhere!]
}

input RoleAssociationInclude {
  permissions: PermissionFilter
  members: UserFilter
}
