type User {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String!
  phoneNumber: String
  picture(resize: ImageResizeInput): String
  language: String!
  emailVerified: Boolean!
  phoneNumberVerified: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime
}

input CreateUserInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  phoneNumber: String
  language: String
}

input UpdateProfileInput {
  firstName: String
  lastName: String
  phoneNumber: String
  language: String
}

type Query {
  me: UserPayload! # allows us to be flexible. Example: We could use the message field to send specific in-app notification 
}

type Mutation {
  requestEmailVerification: RequestResponse!
  requestPhoneNumberVerification(phoneNumber: String!): RequestResponse!
  verifyEmail(token: String!): UserPayload!
  verifyPhoneNumber(token: String!): UserPayload!
  updateProfile(input: UpdateProfileInput!): UserFormMutationResponse!
}

type UserPayload implements Response {
  code: Int!
  success: Boolean!
  message: String!
  user: User
}

type UserFormMutationResponse implements Response & FormErrors {
  code: Int!
  success: Boolean!
  message: String!
  errors: [FieldError!]
  user: User
}