type Query {
  me: UserPayload! @auth
  getUserById(id: ID!): UserPayload! @auth
  users(page: ListPage, filter: UserFilter): UserList! @auth
}

type Mutation {
  updateCurrentUserFullname(input: UpdateFullnameInput!): UserMutationResponse!
    @auth
  updateCurrentUserName(username: String!): UserMutationResponse! @auth
  updateCurrentUserLocale(locale: Locale!): UserMutationResponse! @auth
  removeCurrentUserProfilePicture: UserMutationResponse! @auth
  requestCurrentUserPhoneNumberVerification(
    phoneNumber: PhoneNumber!
  ): UserMutationResponse! @auth
  verifyPhoneNumber(token: String!): UserMutationResponse! @auth

  # Admin
  createUserAccounts(input: CreateUserAccountsInput!): CreateUsersResponse!
    @auth
  updateUserProfile(input: UpdateUserProfileInput!): UserMutationResponse! @auth
  changeAccountStatus(input: ChangeAccountStatusInput!): UserMutationResponse!
    @auth
  deleteUserAccounts(ids: [ID!]!, reason: String): DeleteMutationResponse! @auth
  attachRolesToUser(userId: ID!, roleIds: [ID!]!): UserMutationResponse! @auth
  detachRolesFromUser(userId: ID!, roleIds: [ID!]!): UserMutationResponse! @auth
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  username: String
  email: EmailAddress! @auth(rules: [{ allow: owner, identityClaim: "id" }])
  phoneNumber: PhoneNumber @auth(rules: [{ allow: owner, identityClaim: "id" }])
  picture: Photo
  socialAvatarURL: URL
  isOwner: Boolean!
  locale: Locale!
  emailVerified: Boolean!
  phoneNumberVerified: Boolean!
  roles: [Role]!
  createdAt: DateTime!
  updatedAt: DateTime
  status: AccountStatus! @auth(rules: [{ allow: owner, identityClaim: "id" }])
}

enum AccountStatus {
  SUSPENDED
  BANNED
  LOCKED
  PROVISIONED
  ACTIVE
}

type UserPayload implements Response {
  code: ID!
  success: Boolean!
  message: String!
  user: User
}

type CreateUsersResponse implements Response & FormErrors {
  code: ID!
  success: Boolean!
  message: String!
  errors: [FieldError!]
  users: [User]
}

type UserMutationResponse implements Response & FormErrors {
  code: ID!
  success: Boolean!
  message: String!
  errors: [FieldError!]
  user: User
}

# Inputs

input CreateAccountInput {
  firstName: String!
  lastName: String!
  username: String
  email: EmailAddress!
  password: String!
  phoneNumber: PhoneNumber
  locale: Locale
}

input CreateUserProfileInput {
  firstName: String!
  lastName: String!
  email: EmailAddress!
  phoneNumber: PhoneNumber
  locale: Locale
}

input CreateUserAccountsInput {
  profiles: [CreateUserProfileInput!]!
  roleIds: [ID!]!
}

input UpdateUserProfileInput {
  id: ID!
  firstName: String
  lastName: String
  username: String
  email: EmailAddress
  phoneNumber: PhoneNumber
  locale: Locale
}

input UpdateFullnameInput {
  firstName: String
  lastName: String
}

input ChangeAccountStatusInput {
  id: ID!
  status: AccountStatus!
  reason: String
}

# Pagination

type UserList implements List {
  items: [User]!
  totalCount: Int!
  pageInfo: PageInfo!
}

# Filter

input UserFilter {
  id: IDFieldFilter
  firstName: StringFieldFilter
  lastName: StringFieldFilter
  username: StringFieldFilter
  email: StringFieldFilter
  phoneNumber: StringFieldFilter
  locale: StringFieldFilter
  createdAt: DateTimeFieldFilter
  updatedAt: DateTimeFieldFilter
  roles: RoleFilter
}
