# syntax=docker/dockerfile:1

FROM node:16-alpine AS build
ENV NODE_ENV=production

WORKDIR /app

# Only for Mac M1 chips
RUN apk add --no-cache python3 g++ make

COPY package.json yarn.lock ./

RUN yarn

COPY . .

CMD yarn start 