# syntax=docker/dockerfile:1

FROM node:16 AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install
COPY . .
CMD yarn build

FROM node:16
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY package*.json yarn.lock ./
RUN yarn install
COPY --from=build /app/build ./build
# copy emails, locales, certs, .sequelize, & .env
EXPOSE 4000
RUN yarn start 