type Mutation {
  login(input: LoginInput!): LoginMutationResponse!
  requestEmailOTP(email: String!): AuthMutationResponse!
  requestSmsOTP(phoneNumber: String!): AuthMutationResponse!
  otpLogin(code: String!): AuthMutationResponse!
  socialLogin(input: SocialLoginInput!): AuthLoginMutationResponse!
  register(input: CreateUserInput!): LoginMutationResponse!
}

input LoginInput {
  email: String!
  password: String!
}

enum SocialProvider {
  GOOGLE
  FACEBOOK
}

input SocialLoginInput {
  provider: SocialProvider!
  token: String!
}

type LoginMutationResponse implements MutationResponse & FormErrors {
  success: Boolean!
  message: String!
  errors: [FieldError!]
  token: String
}

type AuthMutationResponse implements MutationResponse {
  success: Boolean!
  message: String!
  token: String
}
