type Mutation {
  registerWithEmail(input: CreateUserInput!): AuthFormMutationResponse!
  loginWithEmail(input: EmailLoginInput!): AuthFormMutationResponse!
  requestEmailVerification(email: String!): AuthMutationResponse!
  requestSmsOTP(phoneNumber: String!): AuthMutationResponse!
  refreshToken(token: String!): AuthMutationResponse!
  loginWithSmsOTP(input: SmsOTPInput!): AuthMutationResponse!
  loginWithSocialProvider(input: SocialLoginInput!): AuthMutationResponse!
  requestPasswordReset(email: String!): AuthMutationResponse!
  resetPassword(input: PasswordResetInput!): AuthMutationResponse!
  requestDeleteAccount: AuthMutationResponse!
  deleteAccount(token: String!): AuthMutationResponse!
  logout: AuthMutationResponse!
}

input EmailLoginInput {
  email: String!
  password: String!
}

input SmsOTPInput {
  phoneNumber: String!
  code: String!
}

enum SocialProvider {
  GOOGLE
  FACEBOOK
}

input SocialLoginInput {
  provider: SocialProvider!
  token: String!
}

input PasswordResetInput {
  password: String!
  confirmPassword: String!
  token: String!
}

type AuthFormMutationResponse implements Response & FormErrors {
  code: Int!
  success: Boolean!
  message: String!
  errors: [FieldError!]
  idToken: String
  accessToken: String
  refreshToken: String
}

type AuthMutationResponse implements Response {
  code: Int!
  success: Boolean!
  message: String!
  idToken: String
  accessToken: String
  refreshToken: String
}
