scalar Date
scalar DateTime

interface MutationResponse {
  code: Int!
  success: Boolean!
  message: String!
}

interface QueryPayload {
  code: Int!
  success: Boolean!
  message: String
}

type FieldError {
  message: String!
  field: String!
}
