type User {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String!
  phoneNumber: String
  locale: String!
  createdAt: DateTime!
  updatedAt: DateTime
}

input CreateUserInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  phoneNumber: String
  locale: String
}

type Query {
  me: User
}
